---
- name: Instanciate local fact for failed_repos
  set_fact:
    failed_repos: []

- name: Create local repo directory
  file:
    path: "{{ item.repo_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  register: repo_creation
  with_items: >
    {{borgbackup_repos
    | rejectattr('repo_path', 'regex', '^ssh://')
    | reject('in', disabled_repos)
    | list
    }}

- include: create-repo.yml
  with_items: >
    {{borgbackup_repos
    | reject('in', disabled_repos)
    | list
    }}
