---
- name: Estimate if installed
  stat:
    path: "{{ borg_executible }}"
  register: executible_stats

- name: Estimate installed version
  command: "{{ borg_executible }} --version"
  when: executible_stats.stat.exists
  register: borg_installed_version
  changed_when: false

- name: Try to parse installed version
  set_fact:
    installed_version:
      "{{
      borg_installed_version.stdout
      | regex_search(regexp,'\\1')
      | first
      }}"
  vars:
    regexp: ^borg ([0-9]+\.[0-9]+\.[0-9]+)$
  when: borg_installed_version.stdout is defined

- debug:
    msg: "Installed version: {{ installed_version }}"
  when: installed_version is defined

- debug:
    msg: "Installed version: <none>"
  when: installed_version is not defined
