---
- name: Estimate if installed
  stat:
    path: "{{ borg_executible }}"
  register: executible_stats

- name: Estimate installed version
  command: "{{ borg_executible }} --version"
  when: executible_stats.stat.exists
  register: borg_installed_version
  changed_when: false
  ignore_errors: true

- name: Try to parse installed version
  set_fact:
    borgbackup_installed_version:
      "{{
      borg_installed_version.stdout
      | regex_search(regexp,'\\1')
      | first
      }}"
  vars:
    regexp: ^borg ([0-9]+\.[0-9]+\.[0-9]+)$
  when: borg_installed_version is defined
    and borg_installed_version.rc is defined
    and borg_installed_version.rc == 0
    and borg_installed_version.stdout is defined

- name: Display installed version
  debug:
    msg: "Installed version: {{ borgbackup_installed_version }}"
  when: borgbackup_installed_version is defined

- name: Display not existing version
  debug:
    msg: "Installed version: <none>"
  when: borgbackup_installed_version is not defined
