---
- include: determine-already-installed-version.yml
- include: determine-latest-available-version.yml
- include: select-version-to-install.yml

- include: download_release.yml
  when: not (borgbackup_linuxold | bool)

- include: download_linuxold_release.yml
  when: borgbackup_linuxold | bool
