---
- include_tasks: determine-already-installed-version.yml
- include_tasks: determine-latest-available-version.yml
- include_tasks: select-version-to-install.yml

- include_tasks: download_release.yml
  when: not (borgbackup_linuxold | bool)

- include_tasks: download_linuxold_release.yml
  when: borgbackup_linuxold | bool
