---
- name: Estimate version to be installed (use set version)
  set_fact:
    borgbackup_version_to_be_installed: "{{ borgbackup_version }}"
  when: borgbackup_version is defined and borgbackup_version | length > 0

- name: Estimate version to be installed (use latest version)
  set_fact:
    borgbackup_version_to_be_installed: "{{ borgbackup_latest_version }}"
  when: borgbackup_version is not defined or borgbackup_version | length < 1

- debug:
    msg: "Version planned to be installed: {{ borgbackup_version_to_be_installed }}"
