---
- include: create-local-repo.yml
  with_items: >
    {{repos
    | rejectattr('repo_path', 'regex', '^ssh://')
    | list
    }}

- include: create-remote-repo.yml
  with_items: >
    {{repos
    | selectattr('repo_path', 'regex', '^ssh://')
    | list
    }}
