---
- name: Create repo directory
  file:
    path: "{{item.repo_path}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  register: repo_creation

- name: Init local encrypted repo
  shell: 'export BORG_PASSPHRASE="{{item.encryption_passphrase}}"; borg init --encryption {{item.encryption_mode}} "{{item.repo_path}}"'
  when: repo_creation.changed
    and (item.encryption_passphrase is defined
    and item.encryption_passphrase | length > 0)
  changed_when: False
  failed_when: False

- name: Init local unencrypted repo
  shell: 'borg init --encryption none "{{item.repo_path}}"'
  when: repo_creation.changed
    and (item.encryption_passphrase is not defined
    or item.encryption_passphrase | length < 1)
  changed_when: False
  failed_when: False
