---
- include: check-parameters.yml

- name: Create repo directory
  file:
    path: "{{repo_path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install package
  apt:
    name: borgbackup
    state: latest
    update_cache: yes
