---
- include: check-parameters.yml
  no_log: False

- name: install package
  apt:
    name: borgbackup
    state: latest
    update_cache: yes

- include: create-repo.yml
- include: setup-private-passphrase-file.yml
- include: setup-borgbackup-script.yml
- include: setup-systemd-service.yml
