---
- include: validation/check-parameters.yml
  no_log: False

- include: install/main.yml

- include: create-repos.yml

- include: setup-private-passphrase-file.yml
  with_items: "{{repos}}"

- include: setup-borgbackup-script.yml
- include: setup-systemd-service.yml
