---
- include_tasks: validation/check-parameters.yml
  no_log: false

- include_tasks: install/main.yml
  when: not (
    borgbackup_install_from_apt | bool
    or borgbackup_install_from_pip | bool
    )

- include_tasks: install-from-apt/main.yml
  when: borgbackup_install_from_apt | bool

- include_tasks: install-from-pip/main.yml
  when: borgbackup_install_from_pip | bool

- name: Filter disabled repos
  set_fact:
    disabled_repos: >
      {{ borgbackup_repos
      | selectattr('disable_repo', 'defined')
      | selectattr('disable_repo', 'eq', True)
      | list
      }}

- include_tasks: repo-creation/create-repos.yml
  when: borgbackup_repos is defined and borgbackup_repos | length > 0

- include_tasks: setup-private-passphrase-file.yml
  with_items: >
    {{borgbackup_repos
    | reject('in', disabled_repos)
    | list
    }}
  when: borgbackup_repos is defined and borgbackup_repos | length > 0

- include_tasks: setup-borgbackup-script.yml
  when: borgbackup_repos is defined and borgbackup_repos | length > 0

- include_tasks: setup-systemd-service.yml
  when: borgbackup_repos is defined and borgbackup_repos | length > 0

- name: Start systemd-managed docker containers
  meta: flush_handlers
