---
- name: Create borgbackup service
  template:
    src: borgbackup.service.j2
    dest: "/etc/systemd/system/borgbackup.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Create borgbackup timer
  template:
    src: borgbackup.timer.j2
    dest: "/etc/systemd/system/borgbackup.timer"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable borgbackup service
  service:
    name: borgbackup.service
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable borgbackup timer
  systemd:
    name: borgbackup.timer
    enabled: true
  notify: Start borgbackup timer
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
