---
- name: Create private working directory
  file:
    path: "{{private_working_directory}}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Setup passphrase file
  copy:
    dest: "{{passphrase_file}}"
    content: "{{encryption_passphrase}}"
    owner: root
    group: root
    mode: 0600
