---
- name: Create borgbackup script directory
  file:
    path: /opt/borgbackup
    state: directory
    owner: root
    group: root
    mode: 0755
  register: repo_creation

- name: Create borgbackup script
  template:
    src: borgbackup.bash.j2
    dest: /opt/borgbackup/borgbackup.bash
    owner: root
    group: root
    mode: 0755
