---
- name: Create private working directory
  file:
    path: "{{ borgbackup_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: item.encryption_passphrase is defined
    and item.encryption_passphrase | length > 0

- name: Setup passphrase file
  copy:
    dest: "{{ borgbackup_working_directory }}/{{ item.passphrase_filename }}"
    content: "{{ item.encryption_passphrase }}"
    owner: root
    group: root
    mode: 0600
  when: item.encryption_passphrase is defined
    and item.encryption_passphrase | length > 0
