---
- name: Create private working directory
  file:
    path: "{{private_working_directory}}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: item.encryption_passphrase is defined
    and item.encryption_passphrase | length > 0

- name: Setup passphrase file
  copy:
    dest: "{{private_working_directory}}/{{item.passphrase_filename}}"
    content: "{{item.encryption_passphrase}}"
    owner: root
    group: root
    mode: 0600
  when: item.encryption_passphrase is defined
    and item.encryption_passphrase | length > 0
