---
- include_tasks: install-from-pip.yml
  when: ansible_distribution_release == 'bullseye'
    or ansible_distribution_release == 'focal'

- include_tasks: install-from-pipx.yml
  when: not(ansible_distribution_release == 'bullseye'
    or ansible_distribution_release == 'focal')
