---
- name: install apt package
  apt:
    name: "borgbackup={{ borgbackup_version }}"
  when: borgbackup_version is defined
    and borgbackup_version | length > 0

- name: install latest apt package
  package:
    name: borgbackup
  when: borgbackup_version is not defined
    or borgbackup_version | length < 1
