---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should provide borg executable
      command: borg --version
      register: borg_version
      changed_when: false
      failed_when:
        borg_version.stdout | regex_search('borg [0-9]+\.[0-9]+\.[0-9]+') | length < 1
