---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: "Include ansible-borgbackup"
      include_role:
        name: "ansible-borgbackup"
      vars:
        borgbackup_version: 1.4.0
