---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-borgbackup-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-borgbackup-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-borgbackup-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-borgbackup-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-borgbackup-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../install-when-exec-is-corrupt/prepare.yml
    converge: ../install-when-exec-is-corrupt/converge.yml
    verify: ../install-when-exec-is-corrupt/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
