---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-borgbackup-focal
    box: generic/ubuntu2004
  - name: ansible-borgbackup-bullseye
    box: generic/debian11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../install-when-exec-is-corrupt/prepare.yml
    converge: ../install-when-exec-is-corrupt/converge.yml
    verify: ../install-when-exec-is-corrupt/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
