---
- name: check 'archive' parameter
  assert:
    that:
      - "archive is defined"
    fail_msg: "parameter 'archive' is not defined"

- name: check 'name' parameter
  assert:
    that:
      - "archive.name is defined"
      - "archive.name | length > 0"
    fail_msg: "parameter 'archive.name' is missing"

- name: check 'paths' parameter
  assert:
    that:
      - "archive.paths is defined"
      - "archive.paths | length > 0"
    fail_msg: "parameter 'archive.paths' is missing or empty"
