---
name: Run tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run default tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test

      - name: Run 'all-parameters' scenario tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s all-parameters

      - name: Run 'install-linux32' scenario tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-linux32

      - name: Run 'install-from-pip' scenario tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-from-pip

      - name: Run 'install-specific-version-from-pip' scenario tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-specific-version-from-pip
